### ISSUE TITLE
Cannot edit with elementor

### ISSUE THREAD

**Issue by Ikeuuuuu** [brainstormforce/header-footer-elementor#828] opened 2024-05-24 12:23 UTC
### Describe the bug:
I can't edit my header and footer beceause the load screen stays on.

### To reproduce:

 Look at the screenshot. It stays like that.

### Expected behavior:
When I click on edit with elementor I want to be able to edit. This doesn't happen

### Screenshots:
![Schermafbeelding 2024-05-24 141643](https://github.com/brainstormforce/header-footer-elementor/assets/170730118/76ea24c7-3e71-4602-9bff-0edfbd8cc45a)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by Ikeuuuuu** [comment] 2024-05-24 12:54
I did in fact had the latest version of the plugin. I deactivated and activated it. It's solved! Thank you very much!!!!

**Comment by Ikeuuuuu** [comment] 2024-06-01 08:32
I have this problem again. 
The plugin elementor header and footer builder is up to date to version 1.6.35
I deactivated the plugin and activated it back and it still doesn't work.
How did this happen? What can I do?
Every plugin in my website is up to date.

**Comment by Syphercode-One** [comment] 2024-06-11 13:06
This is still an issue after latest updated. Deactivated and reactivated plugin. Editor will not load. Every plugin is up to date.

**Comment by mecpcanada** [comment] 2024-06-12 16:52
same

**Comment by drumship3** [comment] 2024-06-13 12:05
same here

**Comment by drumship3** [comment] 2024-06-13 12:18
i went back to 1.6.35 and it fixed it.

**Comment by rochajulian** [comment] 2024-07-02 01:17
I can confirm that this is still an issue. Has anyone been able to find a solution??

**Comment by drumship3** [comment] 2024-07-02 02:03
Use version 1.35Sent from my iPhoneOn Jul 1, 2024, at 8:18 PM, Julian Rocha ***@***.***> wrote:﻿
I can confirm that this is still an issue. Has anyone been able to find a solution??

**Comment by igorbertotti** [comment] 2024-07-08 23:31
The same here after update. I need to fix this issue urgently!

**Comment by drumship3** [comment] 2024-07-09 00:19
If I use plugin version 1.6.35 it works againSent from my iPhoneOn Jul 8, 2024, at 6:32 PM, igorbertotti ***@***.***> wrote:﻿
The same here after update. I need to fix this issue urgently!

**Comment by esterlinpol** [comment] 2024-07-10 22:55
Hello, I am facing the same issue.

I found a workaround, change your permalinks settings to post ID, then back to postname and it starts working. I hope this helps.

**Comment by rochajulian** [comment] 2024-07-13 13:43
Hey everyone. I've updated to 1.6.37 (released yesterday it seems like) and I am now able to edit with Elementor again.

**Comment by drumship3** [comment] 2024-07-13 15:48
Thanks for the news!Sent from my iPhoneOn Jul 13, 2024, at 8:44 AM, Julian Rocha ***@***.***> wrote:﻿
Hey everyone. I've updated to 1.6.37 (released yesterday it seems like) and I am now able to edit with Elementor again.

**Comment by vijetaR** [comment] 2024-07-18 07:56
Hello,

If you encounter issues with the Elementor – Header Footer & Block Template plugins, such as loading problems or editing difficulties, try the following steps:

1. [Flush](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/) the Permalinks
2. Deactivate and reactivate the plugin and see if that helps.
3. Switch to a default theme and check if the issue persists, to switch back to your current theme.
4. Roll back the plugin to an older version and then upgrade to the latest version (if the above steps don’t help). You can roll back using a plugin like [WP Rollback](https://wordpress.org/plugins/wp-rollback/).
5. If you have low memory due to plugins, increase the WordPress memory limit to at least 256M or up to 512M by editing the wp-config.php file. Also, deactivate unused widgets from Elementor Addons plugins to reduce server requests and memory usage. 

After completing these steps, please let us know if the issue is resolved. Your feedback is valuable to us, and it helps us ensure the best possible experience for our users.

**Comment by levantail** [comment] 2024-07-22 19:31
Changing permalinks to use id only and flushing it after fixed an issue for me.

**Comment by ViktorZich** [comment] 2024-07-26 21:02
Зміна постійних посилань спрацювала. Дякую.

**Comment by rar-77** [comment] 2024-08-09 18:54
1. Flush the Permalinks worked. Good!

**Comment by sushmak02** [comment] 2024-09-16 07:47
As we haven't received any activity on this issue recently, we are closing this issue for now. If you still need assistance or have any further questions, please feel free to reopen this issue or create a new one.

**Closed by sushmak02** 2024-09-16 07:47 UTC
Labels: bug
