### ISSUE TITLE
Hamburger menu on mobile is not clickable

### ISSUE THREAD

**Issue by Matth5792** [brainstormforce/header-footer-elementor#827] opened 2024-05-23 15:54 UTC
### Describe the bug:
The hamburger menu cannot been opened 

### To reproduce:
1. Go to [https://monkkey.fr/acronymes/life/oklm/] for instance with mobile
2. Click on the hamburger menu on the right 
3. The menu is not displayed

### Expected behavior:
The mobile menu has to be opened

### Elementor version:
4.20.3

**Comment by vijetaR** [comment] 2024-05-24 06:16
Hi @Matth5792 Thank you for bringing up the issue you encountered. We sincerely apologize for any inconvenience it may have caused. However, after conducting testing on our end, we were unable to reproduce the problem you mentioned.
To better understand and resolve the issue, we kindly request, if you could open a [support ticket](https://brainstormforce.com/open-a-ticket/) with us and provide access to your demo site along with the necessary credentials, we would be more than happy to investigate the matter further.
Thank you for your understanding and assistance. We look forward to resolving this matter for you.

**Closed** 2024-09-16 07:49 UTC
Labels: bug
