### ISSUE TITLE
Bug Title ...

### ISSUE THREAD

**Issue by asaasasaasa** [brainstormforce/header-footer-elementor#808] opened 2024-05-14 13:11 UTC
### Describe the bug:
Hello my all website is crashed because of this elementor header and footer version

### To reproduce:
cant download the version
getting fattal error

**Comment by m1ga** [comment] 2024-05-14 13:15
please check https://github.com/brainstormforce/header-footer-elementor/issues/805 or all recent posts in https://wordpress.org/support/plugin/header-footer-elementor/

**Comment by asaasasaasa** [comment] 2024-05-14 13:18
Even i tried to restored my website like previous so i downgrade the version then even i cant able to access my admin panel so i have to deactivate that plugin but now its not activating tell me the reason

**Comment by asaasasaasa** [comment] 2024-05-14 13:20
Latest even my plugin is not activating

**Comment by asaasasaasa** [comment] 2024-05-14 13:20
This version i have Version 1.6.29

**Comment by m1ga** [comment] 2024-05-14 13:22
you have to download the old version 1.6.28 (https://wordpress.org/plugins/header-footer-elementor/advanced/ at the bottom) and install that. Or remove the one line from the other issue I've linked above and where you've said `I tried everything `

**Comment by asaasasaasa** [comment] 2024-05-14 13:24
If i download this version and add this again i need to edit my all website ?

**Comment by m1ga** [comment] 2024-05-14 13:25
What do you mean bei "edit my all website"? You EITHER install the old version OR edit the file. Both will fix the issue until 1.6.30 is released.

**Comment by asaasasaasa** [comment] 2024-05-14 13:27
My website header and footer is crashed properly, So if i install this version and uninstall latest one do i need to again edit my all website ? thats what am asking

**Comment by m1ga** [comment] 2024-05-14 13:28
no, of course not. And you don't uninstall the version you just override it. But this is not the place to ask these questions. Please use https://wordpress.org/support/plugin/header-footer-elementor/ for that

**Comment by vijetaR** [comment] 2024-05-16 07:49
Hello,

We apologize for the inconvenience that has been caused by the recent issues – "Error messages during plugin activation" and the "Conflict with WP SVG Images plugin". We are pleased to inform you that we have released an update to fix the issues.

Please update the plugin to the latest version 1.6.31 to resolve the issues.

Thank you for your understanding and patience. If you have any further questions or encounter any issues, please let us know.

**Comment by vijetaR** [comment] 2024-06-17 14:24
Hello Everyone,

We hope the latest update of the Elementor Header Footer Builder plugin (v1.6.36) has resolved your issue. If the problem persists, please let us know so we can assist you further. Since we haven't received any recent activity on this issue, we are closing this ticket for now. If you still need assistance or have any further questions, please feel free to reopen this ticket or create a new one.

Thank you.

**Closed by vijetaR** 2024-06-17 14:24 UTC
Labels: bug
