### ISSUE TITLE
Display Rules | Editor not working with version 1.6.25

### ISSUE THREAD

**Issue by ochoarobert1** [brainstormforce/header-footer-elementor#772] opened 2024-02-16 01:03 UTC
### Describe the bug:
I've updated my plugin to version 1.6.25 and the Display Rules is not working anymore. I've turned on my WP_Debug and found this. And also I cannot edit the header

`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /home/u509264518/domains/graduacion.biu.us/public_html/wp-content/plugins/header-footer-elementor/admin/class-hfe-admin.php:197`
`Stack trace:`
`#0 /home/u509264518/domains/graduacion.biu.us/public_html/wp-content/plugins/header-footer-elementor/admin/class-hfe-admin.php(160): HFE_Admin->column_display_location_rules() `
`#1 /home/u509264518/domains/graduacion.biu.us/public_html/wp-includes/class-wp-hook.php(324): HFE_Admin->column_content() `
`#2 /home/u509264518/domains/graduacion.biu.us/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() `
`#3 /home/u509264518/domains/graduacion.biu.us/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() `
`#4 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-posts-list-table.php(1398): do_action() `
`#5 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-list-table.php(1799): WP_Posts_List_Table->column_default() `
`#6 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-posts-list-table.php(1432): WP_List_Table->single_row_columns() `
`#7 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-posts-list-table.php(834): WP_Posts_List_Table->single_row() `
`#8 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-posts-list-table.php(810): WP_Posts_List_Table->_display_rows() `
`#9 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-list-table.php(1709): WP_Posts_List_Table->display_rows() `
`#10 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/includes/class-wp-list-table.php(1636): WP_List_Table->display_rows_or_placeholder() `
`#11 /home/u509264518/domains/graduacion.biu.us/public_html/wp-admin/edit.php(503): WP_List_Table->display() `
`#12 {main} thrown in /home/u509264518/domains/graduacion.biu.us/public_html/wp-content/plugins/header-footer-elementor/admin/class-hfe-admin.php on line 197`

### To reproduce:
1. Go to admin
2. Click on Customize -> Elementor Header & Footer Builder
3. See error

### Expected behavior:
It should show the display rules applied to this header

### Screenshots:
Error shown on customize
![error-1](https://github.com/brainstormforce/header-footer-elementor/assets/4027931/8625f21b-c877-44ae-b9c7-20f1b0e0fdc5)

Version of Elementor and plugin
![error-2](https://github.com/brainstormforce/header-footer-elementor/assets/4027931/4fd09cd6-0f4c-4f3b-886e-cc4eb1e236bb)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### PHP version tested:
PHP 8.0
PHP 8.2

### WordPress version:
WP 6.4.3

### Elementor version:
Elementor 3.19.2

**Comment by vijetaR** [comment] 2024-02-16 07:01
Hi @ochoarobert1, We've done some testing on our end with the latest versions of Elementor Header Footer Builder and Elementor Plugin, but we haven't encountered the issue you're experiencing. Could you please give us more details about the display rules you've set up on your end? If you can, provide the steps you're taking, and perhaps some screenshots or a screencast would help us better understand the problem. This way, we can assist you more effectively.

**Comment by ochoarobert1** [comment] 2024-02-16 13:19
I don't remember putting any special display options, only that this would be a header. In fact I've search the postmeta asignations:

ehf_target_include_locations
`s:68:"a:2:{s:4:"rule";a:1:{i:0;s:12:"basic-global";}s:8:"specific";a:0:{}}";`

ehf_target_exclude_locations
`s:6:"a:0:{}";`

ehf_target_user_roles
s:20:"a:1:{i:0;s:3:"all";}";

ehf_template_type
`type_header`

UPDATE: I've removed all postmeta and re-entered again and now it works. It seems that's something from the initial postmeta assignations. I hope this can help.

**Comment by vijetaR** [comment] 2024-02-19 13:34
Hello @ochoarobert1,

Thank you for the update. We're glad to hear that you were able to resolve the issue by removing and re-entering the post meta. Since it appears that the issue is now resolved, we are moving forward with closing the matter.

However, if you encounter the issue again or need further assistance, please don't hesitate to let us know. We'll be more than happy to help.

**Closed** 2024-02-19 14:07 UTC
Labels: bug
