### ISSUE TITLE
Elementor Builder not working after latest Header & Footer Plugin update

### ISSUE THREAD

**Issue by theGreenders** [brainstormforce/header-footer-elementor#342] opened 2021-01-19 18:00 UTC
After the last update, the header footer module conflicts withElementor builder. Elementor does not load on safe mode either.

### Screenshots:
https://drive.google.com/file/d/1B4hCbdv4KklAJO4JLsW7zR3ogcx0-k_E/view?usp=sharing

### Isolating the problem:
Post, pages, blocks, are still working on the front-end but there's no way to edit a page/post/block or create a new one using Elementor if the Header & Footer plugin is active. All other plugins have been disabled. 

### WordPress version:

4.5.0

### Theme:

Neve - Latest Version

### Elementor version:
Latest

**Comment by pratikshasaman** [comment] 2021-02-02 10:32
Hello @theGreenders,

Apologies for the delay in response!

I had a look into this issue, but I was unable to reproduce it at my end.

Could you please check if flushing the permalinks help? -- https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/.

Looking forward to hearing from you.

Regards,
Pratiksha Samane

**Comment by pratikshasaman** [comment] 2021-02-18 06:08
Hello,

We are closing this query as we did not hear back from you. I hope the step provided helped you.

Please do not hesitate to get back to us if you still face any hurdles.

Regards,
Pratiksha Samane

**Closed by pratikshasaman** 2021-02-18 06:08 UTC
Labels: bug

**Comment by theGreenders** [comment] 2021-02-18 09:37
hi, sorry i missed the notification somehow. 
I think it got fixed by some other plugin update.

Thanks for looking into it.
