### ISSUE TITLE
Crtitical error after last update

### ISSUE THREAD

**Issue by ProjectSeagrass** [brainstormforce/header-footer-elementor#925] opened 2024-10-29 09:30 UTC
![Screenshot 2024-10-28 134527](https://github.com/user-attachments/assets/33560987-637c-4d6d-a239-6e898533f32c)

### To reproduce:
1. Go to 'https://www.projectseagrass.org/'
2. See error

### Screenshots:
![Screenshot 2024-10-29 092622](https://github.com/user-attachments/assets/e05b6ced-78bb-4fe7-b64c-a61617c77e27)

### WordPress version:
  6.6.2

### Elementor version:   3.25.1
  

We recently got  Elementor Pro and were updating to Version 3.25.0 when the issue occured.

**Comment by vijetaR** [comment] 2024-10-29 10:03
Hello,

We apologize for the inconvenience that has been caused by the recent issues. We are pleased to inform you that we have released an update to fix the issues.

Please update the Elementor Header & Footer Builder plugin to the latest version **1.6.45** to resolve the issues.

Thank you for your understanding and patience. If you have any further questions or encounter any issues, please let us know.

**Comment by ProjectSeagrass** [comment] 2024-10-29 10:13
Hello,

We are already on the 1.6.45 version - we updated to this yesterday which was when the issue occured!

Thank you for you help with this

**Comment by ProjectSeagrass** [comment] 2024-10-29 10:14
![Screenshot 2024-10-29 101422](https://github.com/user-attachments/assets/19eea243-59ea-48d5-8724-719b01f27209)

**Comment by vijetaR** [comment] 2024-10-29 14:51
Hello,
We have conducted testing on our end but couldn’t reproduce the issue you mentioned. Please try the steps below and check if the issue is resolved.

1. Flush WordPress [permalinks](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/).
2. Deactivate and reactivate the HFE and Elementor & Pro plugin.
3. Switch to a default WordPress theme, then switch back to your current theme.

If the issue still persists, please open a [support ticket](https://brainstormforce.com/open-a-ticket/) and share access to your demo site so we can investigate further. Thank you for your understanding and assistance, we look forward to resolving this for you!

**Comment by ProjectSeagrass** [comment] 2024-10-29 15:02
Hello,

We have tried the above - the issue seems to be with HFE plugin and Pro but can't work out what

**Comment by vijetaR** [comment] 2024-11-05 11:11
Hi @ProjectSeagrass Could you please confirm if you’ve raised a support ticket on our forum? If the issue still persists, kindly open a [support ticket ](https://brainstormforce.com/open-a-ticket/) and provide access to your demo site with details so we can investigate further. Thank you for your understanding and assistance—we look forward to resolving this for you!

**Comment by vijetaR** [comment] 2024-11-11 17:50
@ProjectSeagrass As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin.

**Closed by vijetaR** 2024-11-11 17:50 UTC
Labels: bug
