### ISSUE TITLE
Glitches while scrolling

### ISSUE THREAD

**Issue by camiel01** [brainstormforce/header-footer-elementor#393] opened 2021-06-27 17:51 UTC
Hello!

When my site was ready I noticed it glitched when I was scrolling on my iPhone. The problem went away when I deactivated this plugin. 

1. Go to https://doubijoux.nl (on your iPhone)
2. Scroll through the site
3. See error

- I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2

### Elementor version:
v3.2.5

**Comment by sushmak02** [comment] 2021-06-28 04:50
Hello @camiel01 

Thank you for contacting us!

I checked your website and I am able to see the reported issue on your site.

I tried to reproduce a similar issue at our end but, it seems to be working fine! I am not sure how HFE is affecting the page scroll on mobile view.

Can you please check on any other page by adding a simple menu created with HFE? This will help us to confirm if it is due to the used saved section in the navigation menu.

If you could open a ticket here for further conversation, we could better help you - [link](https://ultimateelementor.com/support/)

Looking forward to resolving your issue ASAP.

Thank You!

**Comment by pratikshasaman** [comment] 2021-09-29 09:04
Due to inactivity, we are closing this thread. Please feel free to comment if you have any queries.

**Closed by pratikshasaman** 2021-09-29 09:04 UTC
Labels: bug
