### ISSUE TITLE
Header menu dropdown broken

### ISSUE THREAD

**Issue by dthuering** [brainstormforce/header-footer-elementor#816] opened 2024-05-16 17:31 UTC
### Describe the bug:
After upgrading to 1.6.31, our header menu dropdown elements are not clickable anymore. The dropdown opens but closes immediately when the mouse cursor moves.
There are also JS errors in the console on click.

```
frontend.js?ver=1.6.31:655 Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at HTMLAnchorElement.<anonymous> (frontend.js?ver=1.6.31:655:15)
    at HTMLAnchorElement.dispatch (jquery.min.js?ver=3.7.1:2:40035)
    at v.handle (jquery.min.js?ver=3.7.1:2:38006)
(anonymous) @ frontend.js?ver=1.6.31:655
dispatch @ jquery.min.js?ver=3.7.1:2
v.handle @ jquery.min.js?ver=3.7.1:2`
```

### To reproduce:
You can see the error here: https://www.capacityzurich.ch/

### Expected behavior:
Submenu items are clickable

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
recent

### Elementor version:
recent, just updated all and had the SVG error yesterday as well :/

**Comment by vijetaR** [comment] 2024-05-17 06:07
Thank you for bringing the issue you're experiencing to our attention. We apologize for any inconvenience this may have caused. As a temporary fix, could you please add the following CSS code to your stylesheet and check if the issue is resolved?
```
.hfe-nav-menu__layout-horizontal .hfe-nav-menu .sub-menu { 
    display: block !important; 
}
```
We appreciate your cooperation and patience as we work to debug and address the underlying problem. Your feedback is invaluable, and we are committed to resolving this as quickly as possible. To better understand and resolve the issue, we kindly request that you open a [support](https://ultimateelementor.com/support/) ticket with us. Please provide access to your demo site along with the necessary credentials and a description of the issue. We would be more than happy to investigate the matter further.

**Comment by dthuering** [comment] 2024-05-17 06:11
Hello @vijetaR 
Thank you for your reply. Adding the CSS fixed the issue. :) 

Best,
Danny

**Comment by vijetaR** [comment] 2024-05-21 12:05
Hello @dthuering,

Thank you for reporting the issue with the header menu dropdown. We have fixed this issue in our development version.
Please download and test the attached zip file to see if it resolves the problem. Additionally, please remove any previously applied CSS related to this issue before testing. Your feedback would be greatly appreciated. Thank you.

Version: 1.6.33.1 
[header-footer-elementor-1.6.33.1.zip](https://github.com/brainstormforce/header-footer-elementor/files/15389582/header-footer-elementor-1.6.33.1.zip)

**Comment by vijetaR** [comment] 2024-05-24 06:18
Hi @dthuering Please update the plugin to the latest version, which currently is v1.6.34. See if it fixes the issue. Please let us know how you go. Thank You

**Comment by vijetaR** [comment] 2024-06-17 14:19
Hello @dthuering ,

As we haven't received any activity on this issue recently, we are closing this ticket for now. If you still need assistance or have any further questions, please feel free to reopen this ticket or create a new one.

Thank you for your understanding.

**Closed by vijetaR** 2024-06-17 14:19 UTC
Labels: bug

**Comment by dthuering** [comment] 2024-06-17 14:21
Hello, yes, it got lost. It is working now.
