### ISSUE TITLE
Responsive split menu (MENU LOGO MENU) 

### ISSUE THREAD

**Issue by braincrush** [brainstormforce/header-footer-elementor#375] opened 2021-05-22 12:21 UTC
Hi i'm going trough all the documentation i could find but haven't found a solution to my problem yet, i have the above mentioned header setup and when it goes to mobile mode my header turns into two separate hamburgers separated by logo, is there a setting which i can use to rectify this?

Thanks
Seb

**Comment by sushmak02** [comment] 2021-05-24 04:25
Hello Seb,

Thank you for writing in!

The Navigation menu Hamburger issue is not reproducible at our end.

If you could share the screenshot of your issue and few steps to reproduce will help us better understand the problem. 

Looking forward to hearing from you.

**Comment by braincrush** [comment] 2021-05-27 12:25
HI, I've decided to go with different layout option but basically if used default wordpress header in center mode wordpress splits the menu into two menus (left and main) and places the site logo in the middle, once in mobile mode the main menu (not split) is used triggered by hamburger icon, when i tried recreating it using your plugin i got correct menu in desktop but 2 hamburgers in the responsive mode. I will post screenshot of this if i go back to this design again.

thank you.

**Comment by pratikshasaman** [comment] 2021-09-29 09:03
I hope the issue is resolved for you, so we are closing this query as we did not hear back from you. Please do not hesitate to get back to us if you still face any hurdles.

**Closed by pratikshasaman** 2021-09-29 09:03 UTC
