### ISSUE TITLE
Cant edit footer or header directly (loading screen loop) [Resolved]

### ISSUE THREAD

**Issue by IvaNovich-98** [brainstormforce/header-footer-elementor#888] opened 2024-09-20 16:08 UTC
### Describe the bug:

When im going to edit, and going to the plugin directly, i can't edit it, nothing; stays the loading screen in loop. But when I access a page, I can edit that page and then, edit the footer or header through that page.
### To reproduce:

1 . Go to the plugin
2. Click on "edit with elementor"
error: loop
"Fix":
1. Go to pages
2. Click on "edit with elementor"
3. Go to the header or footer and click "edit element"
it works, now you cant edit

### Isolating the problem:

- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

6.6.2

### Elementor version:

Elementor Header & Footer Builder: 1.6.42

**Comment by vijetaR** [comment] 2024-09-21 15:05
Hello @IvaNovich-98, 

Thanks for reporting the issue. We're investigating it, but haven't been able to reproduce the problem on our end.

Please try the following steps and check if the issue gets resolved:
- Flush WordPress [Permalinks](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/).
- Deactivate and reactivate the HFE plugin.
- Switch to a default WordPress theme, then switch back to your current theme.


If the issue still persists, please open a[ support ticket ](https://brainstormforce.com/open-a-ticket/)here so we can gather more details and troubleshoot further. Your feedback will help us resolve this quickly.

**Comment by IvaNovich-98** [comment] 2024-09-23 15:40
Woww, i flushed the permalinks and it works!. Thank you very much.

**Comment by vijetaR** [comment] 2024-10-08 10:06
Thank you for confirming. Since the issue is resolved, I’m closing this thread. Please feel free to reopen or create a new issue if you encounter any further problems.

**Closed by vijetaR** 2024-10-08 10:06 UTC
Labels: bug
