### ISSUE TITLE
My header and footer builder is empty

### ISSUE THREAD

**Issue by Ana888888** [brainstormforce/header-footer-elementor#401] opened 2021-07-08 08:41 UTC
Hello dear people :) 

My problem is this:

I use Elementor Header & Footer Builder, my header and footer are active and visible on the page but they are not in the builder, ie it is empty. How do I find the mentioned and edit it ?  I  tried deactivation-activation but the builder is still empty.

I hope for your help and tnx for reply,
Ana888888

**Comment by Ana888888** [comment] 2021-07-08 08:48
![Header and footer problem](https://user-images.githubusercontent.com/87119512/124892187-f10d2580-dfd9-11eb-9385-2d0811441ecc.png)

**Comment by sushmak02** [comment] 2021-07-08 09:58
Hello @Ana888888,

Thank you for contacting us!

The issue you are facing is weird and not known. Can you please check if you have created a header/footer by using Elementor's Themer Builder?

Please check and let us know!

If the same issue exists then please open a ticket from [here ](https://ultimateelementor.com/contact/). Please share your site URL in the query so, we can check further.

Looking forward to resolving your query ASAP.

**Comment by Ana888888** [comment] 2021-07-08 12:38
So, the Elementors builder shows me that my header and footer are locked and that I can't edit them if I don't have a pro version. I didn’t have the pro version nor do I plan to have it because of the extra cost. For the same reason, I installed the Elementor header and footer plugin one year ago so that I could create it for free and as easily as possible. 

Everything was fine until yesterday when I wanted to change one detail that changed a bit, probably after the update. 
When I deactivate that plugin, there is no header or footer active on site, when i activated it was visible on site again.  Which would mean that I created it exclusively through that plugin. 

Is the reason I didn't find the header and footer (prin screen) because I don't have a pro version and that's why I can't find it?

**Comment by sushmak02** [comment] 2021-07-08 13:44
To check this issue further we will need to take a closer look at your website.

I tried to reproduce the same scenario you stated above, but it seems to be working fine at my end.

Can you please open a ticket from [here](https://ultimateelementor.com/contact/)? So, we can discuss this further and get this issue fixed for you?

**Comment by Ana888888** [comment] 2021-07-09 10:23
Dear Sushmak02,

i opened ticket/topic and now accepting reply but not sure if my question in sent to support team because it seems that i need to pick premium support whitch means i need to pay something... So, will my problem be solved, or i need to pay for help ? I really want to solve this because my bussines is still running and my site looks terible because of header. I just want to know where to find it and edit it...

Thanks,
Ana

**Comment by sushmak02** [comment] 2021-07-09 11:53
No worries!

I have asked our pre-sales support team to assign your ticket to the HFE team.

You might have received an email with a ticket ID from our support portal. Can you please share that Ticket ID?

This will be easy for us to track your ticket.

**Comment by Ana888888** [comment] 2021-07-12 07:04
i didnt recive yet.  :(

**Comment by Ana888888** [comment] 2021-07-14 11:11
Hello, me again,
Checking for ID ticket, I haven't received it.
Thank you

**Comment by sushmak02** [comment] 2021-07-14 12:36
Hello Ana,

We also could not find your query on our support portal. 

Also, once you submit a form from our site then you will receive a confirmation mail with a ticket ID.
Did you enter your email correctly? Can you try submitting the form again?

**Comment by Ana888888** [comment] 2021-07-15 06:53
This is what it looks like after i submitted topic/question:
![ticket](https://user-images.githubusercontent.com/87119512/125742678-99e638be-d4e2-43a8-8604-cc1af44f25d5.png)

**Comment by Ana888888** [comment] 2021-07-15 06:57
Can I get in touch with someone in a simpler way if you still don't see the topic because I've already done this and the problem is still going on and nothing is being solved ? :(

**Comment by sushmak02** [comment] 2021-07-15 07:38
Sorry, @Ana888888, 

We haven't received any queries on our support portal. Can you check once your email spam if you have received any mail from us?

If not then just mail us at support@bsf.io with all the details of the issue you are facing. Also, if you could provide your site details it will be helpful for us to debug your issue ASAP.

**Comment by Ana888888** [comment] 2021-07-15 08:02
Dear Sushma Kure,

Thank you for being kind, approachable and up to date.
In the meantime I found a solution. The problem was stupid and it was up to
another plugin. Now everything is alright.
Thank you very much, once again. :))

Kind regards,
Ana

**Comment by sushmak02** [comment] 2021-07-15 08:53
Hello @Ana888888,
I am glad you figured out this problem. Feel free to get back to us if you face any issues in the future.

**Closed by sushmak02** 2021-07-15 08:53 UTC
Labels: bug
