### ISSUE TITLE
Mobile menu opening outside the screen

### ISSUE THREAD

**Issue by ju-vrk** [brainstormforce/header-footer-elementor#748] opened 2023-12-04 20:20 UTC
I should be able to open the dropdown menu on mobile inside the screen, but it's opening outside

### To reproduce:
1. Go to the page on mobile
2. Click on the hamburger menu
3. See errir

### Expected behavior:
The menu should open inside the screen

### Screenshots:
Here's the [link to a screen recording](https://drive.google.com/file/d/1Hgvp2eTXbmbH6LgNzDrt4kqJ3tLLFx_e/view?usp=sharing) showing the problem and a weird situation where the menu is working (when switching apps): 

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

**Comment by vijetaR** [comment] 2023-12-05 05:02
Hi @ju-vrk, We sincerely apologise for any inconvenience. However, after conducting testing on our end, we were unable to reproduce the problem you mentioned. To better understand and resolve the issue, we kindly request, if you could open a [support](https://ultimateelementor.com/support/) ticket with us and provide access to your demo site along with the necessary credentials and description, we would be more than happy to investigate the matter further. Thank you for your understanding and assistance. We look forward to resolving this matter for you.

**Comment by niilopoutanen** [comment] 2024-03-18 14:18
This is still happening, caused by this line:

var sec_pos = $( '.elementor-element-' + id ).closest('.elementor-section').offset().left - $selector.offset().left;
Uncaught TypeError: Cannot read properties of undefined (reading 'left')

Located in function function _toggleClick( id )
![image](https://github.com/brainstormforce/header-footer-elementor/assets/60819607/b2069280-e64a-4ba8-a73f-a5f1b29a001d)


If "Full width" option is turned off, that kind of fixes the issue, but then the menu will no longer work as expected, so that is not a solution.

**Comment by vijetaR** [comment] 2024-09-17 14:42
Hello @niilopoutanen , @ju-vrk Thank you for bringing this issue to our attention. We have addressed it in [Version 1.6.40.](https://github.com/brainstormforce/header-footer-elementor/releases/tag/v1.6.40) Please update to the latest version and let us know if the problem persists.

Additionally, we have tested the issue on our end and found that the submenu opens properly when clicked. Could you kindly recheck on your side? Here is the screencast for reference: https://bsf.d.pr/v/QNAbYH

If you have any further questions or encounter other issues, feel free to open a [support ticket](https://brainstormforce.com/open-a-ticket/) with us.

**Comment by vijetaR** [comment] 2024-09-20 06:42
Hello @niilopoutanen , @ju-vrk As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.

**Closed by vijetaR** 2024-09-20 06:42 UTC
Labels: bug
