### ISSUE TITLE
Web header - drop down menu problem with arrow

### ISSUE THREAD

**Issue by LaVeronika** [brainstormforce/header-footer-elementor#414] opened 2021-09-01 17:24 UTC
### Screenshots:  
1. screenshot of how it looks when it's without Elementor Header & Footer Builder

![1 Header-original-good](https://user-images.githubusercontent.com/89932879/131715622-d3ddc0ed-be2f-45e1-9176-30847ecb6b93.JPG)

2. how it looks with Elementor Header & Footer Builder.

![2 Header-with header-and-footer-builder-bad](https://user-images.githubusercontent.com/89932879/131715701-9972a3b2-efe6-4197-b897-c20a7e8f4285.JPG)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by sushmak02** [comment] 2021-09-02 05:17
Hello @LaVeronika,

Thank you for contacting us!

I checked the Navigation Menu dropdown icon and it's working fine at our end. I could not reproduce the same issue at our end.

For debugging purposes check if this helps - https://share.getcloudapp.com/Wnu0qRpN
Change the Font Awesome 4 setting to yes if already not enabled. This will help us in tracking the cause of the issue.

Also, we will need to take a look at your website where this issue exists. If you could share the URL of your website it will be easy for us to debug further.

Thank you!

**Comment by LaVeronika** [comment] 2021-09-02 12:44
Heslo,

thank you for the email. Take a look on http://www.lesniduse.cz/kdo-jsem/.
I am not able to use getclpudapp.com now, plese help me, I use Header and
footer builder first time and it seems, that all settings is good.

Thanks and best regards,
Veronika


Dne čt 2. 9. 2021 7:18 uživatel Sushma Kure ***@***.***>
napsal:

**Comment by sushmak02** [comment] 2021-09-03 05:28
Hello @LaVeronika 

I can see the issue on your site.

To debug the issue further I inspected that element in the browser and I can see the <i> tag is getting replaced by inline SVG.

Can you check this by changing this setting from Elementor - https://share.getcloudapp.com/d5uRNb9z

This will help us in further debugging the issue.

**Comment by pratikshasaman** [comment] 2021-09-29 09:04
I hope the issue is resolved for you, so we are closing this query as we did not hear back from you. Please do not hesitate to get back to us if you still face any hurdles.

**Closed by pratikshasaman** 2021-09-29 09:04 UTC
Labels: bug

**Comment by LaVeronika** [comment] 2021-09-29 11:28
Halo,

thank you for your info, but the problem I have still. Everything is set
how you advise, but the arrows are missing... ☹ You can see on
http://www.lesniduse.cz/

The website is now mentioned on some events and it is very unkind, is not
perfect

Tgank you if you can check up or something.

Best regards, Veronika

Dne st 29. 9. 2021 11:04 uživatel Pratiksha Samane ***@***.***>
napsal:
