### ISSUE TITLE
Bug Title ...

### ISSUE THREAD

**Issue by CB19091** [brainstormforce/header-footer-elementor#720] opened 2023-09-08 10:37 UTC
![image](https://github.com/brainstormforce/header-footer-elementor/assets/62895856/9922792f-bc40-45f9-9f2b-26f7f752b7ef)
### WordPress version:
6.3.1

### Elementor version:
Elementor v3.15.3

There is an overflow issue with all the pages except the Homepage. As shown in the image you get 2 scroll bars and there is an empty blank space after the footer. However its weird when you hover over the last menu item on the header the bug fixes automatically.

**Comment by vijetaR** [comment] 2023-09-14 14:16
Hi @CB19091 We are not able to reproduce this issue on our end. To better understand and resolve the issue, we kindly request, if you could open a [support ticket ](https://brainstormforce.com/open-a-ticket/)with us and provide access to your demo site along with the necessary credentials, we would be more than happy to investigate the matter further.

**Comment by CB19091** [comment] 2023-09-15 06:15
Thank you! I have opened a ticket as instructed

**Comment by vijetaR** [comment] 2023-09-27 04:31
Hello @CB19091, We wanted to inform you that the issue you reported has already been successfully resolved in the ticket you previously opened with us. We're delighted to let you know that our team has taken care of this matter, and your website should now be free from the issue you encountered.

**Closed by vijetaR** 2023-09-27 04:31 UTC
Labels: bug
