### ISSUE TITLE
Anchor link bug

### ISSUE THREAD

**Issue by Mosae** [brainstormforce/header-footer-elementor#761] opened 2024-01-16 16:17 UTC
### Describe the bug:

Header Anchor menu items under Committee forces the page to reload and redirect to /gallery/#main 

### Expected behavior:

The clicking on different anchor links should not redirect to /gallery/#main

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:

6.4.2

### Elementor version:
Version 3.18.3

**Comment by vijetaR** [comment] 2024-05-24 06:31
Hi @Mosae I understand you’re experiencing an issue. Could you please provide detailed steps to reproduce it? 
Additionally, to better understand and resolve the issue, we kindly request, if you could open a [support ticket](https://brainstormforce.com/open-a-ticket/) with us and provide access to your demo site along with the necessary credentials, we would be more than happy to investigate the matter further. Thank you for your understanding and assistance. We look forward to resolving this matter for you.

**Comment by vijetaR** [comment] 2024-09-17 18:16
Hello @Mosae @ldevesa, We're sorry for the trouble caused. We tested the issue you reported, and we couldn’t reproduce it on our end. Please update to the latest version of the Header & Footer for Elementor version 1.6.42 and check if the issue still occurs.  Here is a [screencast]( https://bsf.d.pr/v/zgOJWg) showing our test. If you continue to have trouble, please open a [support](https://brainstormforce.com/open-a-ticket/) ticket for further assistance.
Thank you!

**Comment by vijetaR** [comment] 2024-09-20 06:44
Hello @Mosae @ldevesa, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.

**Closed by vijetaR** 2024-09-20 06:44 UTC
Labels: bug
