### ISSUE TITLE
Fatal error with version 1.6.30

### ISSUE THREAD

**Issue by Elisa8321** [brainstormforce/header-footer-elementor#810] opened 2024-05-14 14:37 UTC
### Describe the bug:
After getting a fatal error with version 1.6.29 I updated to 1.6.30 but it triggers a fatal error anyway..and I get this message: An error of type E_COMPILE_ERROR was caused in line 16 of the file /homepages/12/d495428187/htdocs/app497430624/wp-content/plugins/header-footer-elementor/inc/lib/svg-sanitizer/src/Sanitizer.php. Error message: Cannot declare class enshrined\svgSanitize\Sanitizer, because the name is already in use

With version 1.6.29 it was something in line 32 causing a compile error

### WordPress version:
6.5.3

### Elementor version:
3.21.5

**Comment by themuddfamily** [comment] 2024-05-14 14:42
+1 also getting this issue

**Comment by bellottidesign** [comment] 2024-05-14 14:49
The current situation is very unfortunate. I noticed the bug this morning when I wanted to set up a new instance for a customer and received the said error on the 32 line with version 1.6.29.

Fortunately, I was able to fall back to version 1.6.28 on an alternative instance that I had set up yesterday.

Let's hope that the bug can be completely fixed with 1.6.31.

**Comment by m1ga** [comment] 2024-05-14 14:57
> If permitted, I can also upload the .zip for version 1.6.28 here.

you can always download older versions at the normal plugin page: https://wordpress.org/plugins/header-footer-elementor/advanced/ (at the bottom). No need to upload ZIP files here

**Comment by PeculiarHead** [comment] 2024-05-14 14:58
I did the exact same thing. My site was dead, so I rolled back to 1.6.28 and all was well again. So we'll just wait for 1.6.30 and it's not a big deal (as I haven't read the release notes to see what was updated, but 28 currently works fine for me). Cheers.

**Comment by m1ga** [comment] 2024-05-14 14:59
https://github.com/brainstormforce/header-footer-elementor/pull/811 will hopefully fix all issues. Perhaps they'll test it this time :wink:

**Comment by 0xK3on** [comment] 2024-05-14 15:00
> I did the exact same thing. My site was dead, so I rolled back to 1.6.28 and all was well again. So we'll just wait for 1.6.30 and it's not a big deal (as I haven't read the release notes to see what was updated, but 28 currently works fine for me). Cheers.

FATAL error is not a big deal? I woke up with a phone call from my client complaining his website is DEAD!!!

**Comment by rchacin** [comment] 2024-05-14 15:26
Fatal error: Cannot declare class enshrined\svgSanitize\Sanitizer, because the name is already in use in /****/wp-content/plugins/header-footer-elementor/inc/lib/svg-sanitizer/src/Sanitizer.php on line 16

**Comment by rchacin** [comment] 2024-05-14 15:30
Fatal error: Cannot declare class enshrined\svgSanitize\Sanitizer, because the name is already in use  .... Sanitizer.php on line 16

**Comment by rchacin** [comment] 2024-05-14 15:49
> For the fatal error regarding the sanitizer, we are providing a zip file for the fix v1.6.30. Here is the link to the zip: [header-footer-elementor.zip](https://github.com/brainstormforce/header-footer-elementor/files/15310839/header-footer-elementor.zip)
> 
> Can you please verify if it's working as expected, as we are unable to replicate it on our end.

Yes..! It's working for me! THX

**Comment by m1ga** [comment] 2024-05-14 15:54
@rchacin are you using any other svg plugin like svg-support? As that is using svgSanitize too. Maybe that is something to test @vijetaR

**Comment by rchacin** [comment] 2024-05-14 15:57
> @rchacin are you using any other svg plugin like svg-support? As that is using svgSanitize too. Maybe that is something to test @vijetaR

That is absolutely right. I'm using WP SVG Images on the particular site that was failing.

**Comment by digimarkup** [comment] 2024-05-15 04:31
@vijetaR You can just add the svg support plugin to replicate it on your end. The provided file fixed the issue. Can you please make sure this does not happen again in the next update. I just spent hours manually updating over 50 websites.

**Comment by tbscode** [comment] 2024-05-15 07:15
Same issue here, sightly different error message:

```bash
PHP Fatal error:  Cannot declare class enshrined\svgSanitize\Sanitizer, because the name is already in use in /bitnami/ │
│ 202.61.241.62 - - [15/May/2024:06:32:43 +0000] "GET /wp-login.php HTTP/1.1"
```

Using the [bitnami wp helm chart](https://bitnami.com/stack/wordpress/helm) for deployment.

Auto-update brought our WP site down, only fix was to manually move the plugin out of `wp-content/plugins` and then re-install the reverted version.

What caused the issue exactly? That was a surprise to find our page down this morning ;)

**Comment by Elodie12345** [comment] 2024-05-15 07:22
Hello, 

I have the same problem but since i'm on wordpress.com I cant restore a previous version.
My dashboard on wordpress won't let me access the plugins, or the versions of the plugins (it can't even see the plugins that were installed!!) and I can't even see the theme or do anything about it ! 
Can someone please help me ?

**Comment by Elisa8321** [comment] 2024-05-15 07:33
Hi,

just go here: https://wordpress.org/plugins/header-footer-elementor/advanced/
and at the bottom of the page you can choose which version you would like to download (1.6.28 fixed the issue yesterday for me). Then you can install it manually on wordpress (add new plugin, upload .zip file).

They just released version 1.6.31 and it works for me.

Elisa

—

Elisa Miotti

M  +39 380 3110833

**Comment by danielmarschall** [comment] 2024-05-15 08:04
Don't you test your plugin at all before you roll out to millions of websites?!

Yesterday, auto-update to 1.6.29 broke our website, because include to vendor/autoload.php failed, because this file is not existing. Commented out and waited for the hotfox 1.6.30 to come.

Today, auto-update to 1.6.30 and page down again, because of a conflict with class Sanitizer.

Luckily, I know how to look at PHP error logs and comment out the code pieces which are faulty. But other wordpress website owners do not have that experience and will have a broken site which they cannot login to anymore.

I am a software developer myself and I know that bugs do happen. But such trivial bugs could have been detected by just testing the thing or by running tools like PHPstan to detect mistakes like including files which are not existing.

I will disable auto-update now.

**Comment by themuddfamily** [comment] 2024-05-15 08:23
> Don't you test your plugin at all before you roll out to millions of websites?!
> 
> Yesterday, auto-update to 1.6.29 broke our website, because include to vendor/autoload.php failed, because this file is not existing. Commented out and waited for the hotfox 1.6.30 to come.
> 
> Today, auto-update to 1.6.30 and page down again, because of a conflict with class Sanitizer.
> 
> Luckily, I know how to look at PHP error logs and comment out the code pieces which are faulty. But other wordpress website owners do not have that experience and will have a broken site which they cannot login to anymore.
> 
> I am a software developer myself and I know that bugs do happen. But such trivial bugs could have been detected by just testing the thing or by running tools like PHPstan to detect mistakes like including files which are not existing.
> 
> I will disable auto-update now.

Im very surprised this happened, if you look at the commits list the automated tests failed on the merge that caused it, thats when they should have caught this... even if they aren't testing manually this should be sending them an email saying testing failed!

**Comment by vijetaR** [comment] 2024-05-16 07:42
Hello,

We apologize for the inconvenience that has been caused by the recent issues – "Error messages during plugin activation" and the "Conflict with WP SVG Images plugin". We are pleased to inform you that we have released an update to fix the issues.

Please update the plugin to the latest version 1.6.31 to resolve the issues.

Thank you for your understanding and patience. If you have any further questions or encounter any issues, please let us know.

**Comment by juanpahv** [comment] 2024-05-16 16:43
can anyone confirm if 1.6.31 is already working? I'm about to rollback to 1.6.28

**Comment by rchacin** [comment] 2024-05-16 16:46
Yes, no issues with .31

# Enviado desde mi dispositivo móvil #

**Comment by vijetaR** [comment] 2024-05-24 06:23
Hello Everyone, The current plugin version is 1.6.34 So, I would suggest you to update the EHFB plugin to the latest version to resolve the issue. Thanks for understanding!

**Comment by vijetaR** [comment] 2024-06-17 14:18
Hello Everyone,

Thank you for your patience.

As we haven't received any activity on this issue recently, we are closing this ticket for now. If you still need assistance or have any further questions, please feel free to reopen this ticket or create a new one.

Thank you for your understanding.

**Closed by vijetaR** 2024-06-17 14:18 UTC
Labels: bug
