### ISSUE TITLE
Header is broken 

### ISSUE THREAD

**Issue by lorieng7** [brainstormforce/header-footer-elementor#845] opened 2024-06-16 21:40 UTC
### Describe the bug:
my header and menu are no longer appearing 

### To reproduce:
cannot be reproduced on another site. I had to deactivate the app and the menu reappeared 

### Expected behavior:
menu should show but it is hidden

### Screenshots:
2 screen shots attached. one with no menu with app activated 

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
6.5.4
![Uploading Screenshot 2024-06-16 at 22.34.40.png…]()

### Elementor version:
3.22.0

**Comment by moralesgoyo** [comment] 2024-06-17 13:51
Same issue, 

When the plugin is activated, site breaks.


<img width="2222" alt="Captura de pantalla 2024-06-17 a las 14 50 17" src="https://github.com/brainstormforce/header-footer-elementor/assets/173069875/efc337da-8c38-4813-865e-d9845e9dd1be">
<img width="2233" alt="Captura de pantalla 2024-06-17 a las 14 50 25" src="https://github.com/brainstormforce/header-footer-elementor/assets/173069875/8a91bb3e-5b53-4d1e-8a37-d490a44bf263">

**Comment by moralesgoyo** [comment] 2024-06-17 13:52
https://milan16farmacia.com/

**Comment by vijetaR** [comment] 2024-06-18 06:08
Hi @lorieng7 @moralesgoyo 

Thank you for bringing up the issue you encountered. We sincerely apologize for any inconvenience it may have caused. However, after conducting testing on our end, we were unable to reproduce the problem you mentioned. 

To better understand and resolve the issue, we kindly request, if you could open a [support ticket ](https://brainstormforce.com/open-a-ticket/)with us and provide access to your demo site along with the necessary credentials and steps to reproduce, we would be more than happy to investigate the matter further. 

Thank you for your understanding and assistance. We look forward to resolving this matter for you.

**Comment by vijetaR** [comment] 2024-07-18 08:02
Hello @lorieng7 @moralesgoyo 

As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.

**Closed by vijetaR** 2024-07-18 08:02 UTC
Labels: bug
