### ISSUE TITLE
My main menu and footer disappeared suddenly

### ISSUE THREAD

**Issue by tipstpo** [brainstormforce/header-footer-elementor#868] opened 2024-08-23 15:48 UTC
### Describe the bug:
The plugins are automaticly updated, I didnt touch anything, suddenly my menu and footer disappeared.

### To reproduce:
Go to www.tipstpo.com

and you wont see the usual menu and footer like before.

### Expected behavior:
Be visible the menu and the footer

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
Wordpress 6.6.1

### Elementor version:
Elementor 3.23.4

**Comment by vijetaR** [comment] 2024-08-24 09:52
Hello @tipstpo, If you encounter issues with the Elementor – Header Footer, such as loading problems or editing difficulties, try the following steps:

1. Deactivate and Reactivate the HFE plugin.
2. Switch to a default WordPress theme and then switch back to your current theme.
3. [Flush](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/) the Permalinks
4. Remove HFE plugin and reinstall it.

In addition, could you please provide the name and version of the theme and plugins you are currently using? This information will help us better understand the context of the issue.

**Comment by tipstpo** [comment] 2024-08-26 19:09
Hi,

Nothing of that worked out unfortunatelly.

About your question:
Theme: Astra
Plugin:Elementor Header & Footer Builder Versión 1.6.39

Let me know if you need anything else. And keep me updated please

Sergio
    En sábado, 24 de agosto de 2024, 11:52:46 CEST, Vijeta Raikar ***@***.***> escribió:  
 
 


Hello @tipstpo, If you encounter issues with the Elementor – Header Footer, such as loading problems or editing difficulties, try the following steps:
   
   - Deactivate and Reactivate the HFE plugin.
   - Switch to a default WordPress theme and then switch back to your current theme.
   - Flush the Permalinks
   - Remove HFE plugin and reinstall it.

In addition, could you please provide the name and version of the theme and plugins you are currently using? This information will help us better understand the context of the issue.

**Comment by tipstpo** [comment] 2024-09-02 09:28
Hi!

Any update?

Sergio
    En lunes, 26 de agosto de 2024, 21:09:12 CEST, Sergio Pérez cascant ***@***.***> escribió:  
 
  Hi,

Nothing of that worked out unfortunatelly.

About your question:
Theme: Astra
Plugin:Elementor Header & Footer Builder Versión 1.6.39

Let me know if you need anything else. And keep me updated please

Sergio
    En sábado, 24 de agosto de 2024, 11:52:46 CEST, Vijeta Raikar ***@***.***> escribió:  
 
 


Hello @tipstpo, If you encounter issues with the Elementor – Header Footer, such as loading problems or editing difficulties, try the following steps:
   
   - Deactivate and Reactivate the HFE plugin.
   - Switch to a default WordPress theme and then switch back to your current theme.
   - Flush the Permalinks
   - Remove HFE plugin and reinstall it.

In addition, could you please provide the name and version of the theme and plugins you are currently using? This information will help us better understand the context of the issue.

**Comment by vijetaR** [comment] 2024-09-03 04:47
Hi @tipstpo, Thank you for letting us know about the issue. We're sorry for the trouble caused by the menu and footer disappearing after the plugin updates. After checking on our end, we couldn't replicate the issue you described. To help you better, could you please open a [support ticket](https://brainstormforce.com/open-a-ticket/) and share access to your staging site? This will allow us to investigate and fix the issue directly. Thanks for your cooperation. We look forward to resolving this for you.

**Comment by tipstpo** [comment] 2024-09-11 14:44
Hi!

Any update?

Sergio
    En martes, 3 de septiembre de 2024, 06:48:00 CEST, Vijeta Raikar ***@***.***> escribió:  
 
 


Hi @tipstpo, Thank you for letting us know about the issue. We're sorry for the trouble caused by the menu and footer disappearing after the plugin updates. After checking on our end, we couldn't replicate the issue you described. To help you better, could you please open a support ticket and share access to your staging site? This will allow us to investigate and fix the issue directly. Thanks for your cooperation. We look forward to resolving this for you.

**Comment by AnkushT-12** [comment] 2024-09-16 07:36
Hi @tipstpo,

We have already resolved the disappearing header issue that you were facing. As mentioned in the ticket you have enabled the Elementer Offcanvas Page Template. This layout removes the site's header, footer, and sidebars, which is why the Header and Footer created with the Elementor Header & Footer Builder (EHF) were not visible. You can find more details about this layout here: [Elementor Canvas Page Template](https://elementor.com/help/using-elementors-canvas-page-template).

To fix the issue, we have changed the Page Layout to the Default Theme.


I hope that helps.

**Comment by tipstpo** [comment] 2024-09-16 07:43
Now its working! I dont know how that Elementor offcanvas page template was enabled, maybe was something automatic, no idea. But I appreciate the help! good job!

Thanks!
Sergio
    En lunes, 16 de septiembre de 2024, 09:36:53 CEST, AnkushT ***@***.***> escribió:  
 
 


Hi @tipstpo,

We have already resolved the disappearing header issue that you were facing. As mentioned in the ticket you have enabled the Elementer Offcanvas Page Template. This layout removes the site's header, footer, and sidebars, which is why the Header and Footer created with the Elementor Header & Footer Builder (EHF) were not visible. You can find more details about this layout here: Elementor Canvas Page Template.

To fix the issue, we have changed the Page Layout to the Default Theme.

I hope that helps.

**Closed** 2024-09-16 07:46 UTC
Labels: bug
