### ISSUE TITLE
Elementor menu not working on mobile devices.

### ISSUE THREAD

**Issue by Shinig4mi** [brainstormforce/header-footer-elementor#856] opened 2024-08-05 17:36 UTC
The navigation menu is not clicking or working on a mobile device.
Please advice.

**Comment by vijetaR** [comment] 2024-09-17 04:52
Hi @Shinig4mi, thank you for letting us know about the issue. We're sorry for the trouble caused by the menu not working. After checking on our end, we couldn't replicate the issue you described. To help you better, could you please open a [support ticket](https://brainstormforce.com/open-a-ticket/) and share access to your staging site? This will allow us to investigate and fix the issue directly. Thanks for your cooperation. We look forward to resolving this for you.

**Comment by vijetaR** [comment] 2024-09-20 06:48
Hello @Shinig4mi, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.

**Closed by vijetaR** 2024-09-20 06:48 UTC
Labels: bug
