### ISSUE TITLE
An item in menu is highlighted as "active" even though I am on a different site from the menu

### ISSUE THREAD

**Issue by Bradzu** [brainstormforce/header-footer-elementor#879] opened 2024-09-05 10:39 UTC
No matter where I go on my website, in the navbar, only the first item is highlighted as "active". Sometimes nothing gets highlighted at all. Only when I hover over an item.

**Comment by m-yucel** [comment] 2024-09-08 13:25
Same here, also this is causing the multilang link problem, because polylang is generating the link for the active page.

**Comment by oleg-mastriukov** [comment] 2024-09-09 20:22
Same here

**Comment by anjanphukan** [comment] 2024-09-10 06:03
Same here

**Comment by m-yucel** [comment] 2024-09-10 08:07
You can use 1.6.39 version, until they fix.
This solved my problem.
https://downloads.wordpress.org/plugin/header-footer-elementor.1.6.39.zip

**Comment by vijetaR** [comment] 2024-09-11 12:10
Hello, Thank you for letting us know about the error. We really appreciate your help in bringing it to our attention. Further to that, we have successfully reproduced the issue on our end and have taken note of the problem. The fix will be resolved as soon as possible.

**Comment by vijetaR** [comment] 2024-09-17 04:49
Apologies for the trouble. The issue in the Elementor Header & Footer Builder plugin has been fixed in the latest update (version 1.6.42). Please install this update to resolve the issue. Let us know if you face any more issues after updating. Thank you!

**Closed** 2024-09-17 10:34 UTC
Labels: bug
