### ISSUE TITLE
Header-footer-elementor crashes my site

### ISSUE THREAD

**Issue by normpara** [brainstormforce/header-footer-elementor#520] opened 2022-04-19 02:19 UTC
### Describe the bug:
 The plugin was working fine with elementor, but all of a sudden it crashed the website - see screenshots. Disabling the plugin brings the site back up.

### Screenshots:

![image](https://user-images.githubusercontent.com/103976005/163906247-4617292a-cff8-44d4-931c-7124cc9e6336.png)
![image](https://user-images.githubusercontent.com/103976005/163906572-c83ff274-1b5a-4802-a9a6-8d028b2f0020.png)

 I am running WordPress 5.5.9 with the  Astra theme

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by gaurav-jangam** [comment] 2022-04-19 05:57
Hello @normpara,

Thank you for getting in touch with us.

We tried creating a similar scenario and tested it. Everything worked fine at our end.
It's very hard to determine the cause of the issue without looking into your site. I would request If you could share the URL of your site so that we can take a look at it and debug the issue.

Waiting for a response.

**Comment by normpara** [comment] 2022-04-19 16:10
Thank you for looking into this.

The URL is https://healthwiseoptimummassage.com/

Thanks

Norm

**Comment by gaurav-jangam** [comment] 2022-04-20 12:21
Hello @normpara,

I have visited your website, and it seems that you are currently using Astra Header on your website, and I could not check the issue. 

So I would suggest you open a ticket from our support portal link here - https://brainstormforce.com/open-a-ticket/


Also, please share detailed information about the issue so we can check the issue in depth.

We are looking forward to resolving the issue asap.

**Comment by vijetaR** [comment] 2023-09-14 08:50
Hi @normpara, I have visited the above site link, seems to be working correctly. As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.

**Closed by vijetaR** 2023-09-14 08:50 UTC
Labels: bug
