### ISSUE TITLE
Last update to 1.6.18 broke my Header and Footer due to incorrect rendering of SVG image and the menu button

### ISSUE THREAD

**Issue by hass002** [brainstormforce/header-footer-elementor#757] opened 2024-01-13 07:16 UTC
Hi team,

Could you please check for me that When I update the Elementor Header & Footer Builder to Version 1.6.18,

our header on our website crashes:

![13 01 24](https://github.com/brainstormforce/header-footer-elementor/assets/156501554/63263df9-9301-419b-8024-9cf18ea34c73)

And the hamburger bar(menu button) can't work. I have also rolled back in the previous version the issue is not solved.

but in the editor mode when I entered the header editor mode where looked fine 
![13 01 24 new](https://github.com/brainstormforce/header-footer-elementor/assets/156501554/64da7d1d-6576-4e28-af90-cfa438fa1dce)

We're using the following plugins:

Elementor: Version 3.18.3
Elementor Header & Footer Builder: Version 1.6.23
Elementor Addon Elements: Version 5.9.3

Thanks so much!

I'm looking forward to your prompt reply.

Kind Regards

**Comment by vijetaR** [comment] 2024-01-13 14:07
Hello @hass002,
We appreciate you bringing up the problem you faced, and we apologize for any inconvenience it may have caused. We've tested on our end but, we were unable to reproduce the problem you mentioned. To assist you better, could you please open a [support](https://brainstormforce.com/open-a-ticket/) ticket, share access to your demo staging site, and provide the required credentials and steps to reproduce the issue? This will allow us to investigate the matter more thoroughly. Thank you for your understanding, and we look forward to resolving this matter for you.

**Comment by vijetaR** [comment] 2024-07-18 07:59
Hello @hass002 

As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.

**Closed by vijetaR** 2024-07-18 07:59 UTC
Labels: bug
